Repository harvester/harvester, pull requests merged in 2024-09, with the labels that each got.

#6445 Add retry in `deleting a vm and its volume` integration test
  tests/integration/api/vm_apis_test.go
Labels: kind/enhancement, area/ci, area/test

#6149 Introduce scheduled VM backups/snapshots
  deploy/charts/harvester-crd/templates/harvesterhci.io_schedulevmbackups.yaml
  pkg/apis/harvesterhci.io/v1beta1/openapi_generated.go
  pkg/apis/harvesterhci.io/v1beta1/schedulebackup.go
  pkg/apis/harvesterhci.io/v1beta1/zz_generated_deepcopy.go
  pkg/apis/harvesterhci.io/v1beta1/zz_generated_list_types.go
  pkg/apis/harvesterhci.io/v1beta1/zz_generated_register.go
  pkg/codegen/main.go
  pkg/config/context.go
  pkg/controller/master/image/register.go
  pkg/controller/master/schedulevmbackup/common.go
  pkg/controller/master/schedulevmbackup/common_test.go
  pkg/controller/master/schedulevmbackup/cronjob.go
  pkg/controller/master/schedulevmbackup/register.go
  pkg/controller/master/schedulevmbackup/svmbackup.go
  pkg/controller/master/schedulevmbackup/vmbackup.go
  pkg/controller/master/setup.go
  pkg/data/crd.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/generated/clientset/versioned/typed/batch/v1/batch_client.go
  pkg/generated/clientset/versioned/typed/batch/v1/cronjob.go
  pkg/generated/clientset/versioned/typed/batch/v1/doc.go
  pkg/generated/clientset/versioned/typed/batch/v1/fake/doc.go
  pkg/generated/clientset/versioned/typed/batch/v1/fake/fake_batch_client.go
  pkg/generated/clientset/versioned/typed/batch/v1/fake/fake_cronjob.go
  pkg/generated/clientset/versioned/typed/batch/v1/fake/fake_job.go
  pkg/generated/clientset/versioned/typed/batch/v1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/batch/v1/job.go
  pkg/generated/clientset/versioned/typed/harvesterhci.io/v1beta1/fake/fake_harvesterhci.io_client.go
  pkg/generated/clientset/versioned/typed/harvesterhci.io/v1beta1/fake/fake_schedulevmbackup.go
  pkg/generated/clientset/versioned/typed/harvesterhci.io/v1beta1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/harvesterhci.io/v1beta1/harvesterhci.io_client.go
  pkg/generated/clientset/versioned/typed/harvesterhci.io/v1beta1/schedulevmbackup.go
  pkg/generated/controllers/batch/factory.go
  pkg/generated/controllers/batch/interface.go
  pkg/generated/controllers/batch/v1/cronjob.go
  pkg/generated/controllers/batch/v1/interface.go
  pkg/generated/controllers/harvesterhci.io/v1beta1/interface.go
  pkg/generated/controllers/harvesterhci.io/v1beta1/schedulevmbackup.go
  pkg/generated/controllers/longhorn.io/v1beta2/interface.go
  pkg/generated/controllers/longhorn.io/v1beta2/snapshot.go
  pkg/util/constants.go
  pkg/util/fakeclients/cronjob.go
  pkg/util/fakeclients/svmbackup.go
  pkg/util/fakeclients/vmbackup.go
  pkg/util/svmbackup.go
  pkg/webhook/indexeres/indexer.go
  pkg/webhook/resources/schedulevmbackup/validator.go
  pkg/webhook/resources/virtualmachinebackup/validator.go
  pkg/webhook/resources/virtualmachinerestore/validator.go
  pkg/webhook/server/validation.go
  scripts/known-api-rule-violations.txt
Labels: backport-to/v1.4

#6349 fix(upgradelog): adapt to new extravolume mechanics
  pkg/api/upgradelog/handler.go
  pkg/controller/master/upgradelog/common.go
  pkg/controller/master/upgradelog/controller.go
  pkg/controller/master/upgradelog/controller_test.go
  pkg/controller/master/upgradelog/register.go
Labels: backport-to/v1.4

#6517 Enhance cpu pinning
  deploy/charts/harvester/templates/configmap.yaml
  pkg/controller/master/node/cpu_manager_controller.go
  pkg/util/constants.go
  pkg/webhook/resources/node/validator.go
Labels: backport-to/v1.4

#6478 Hardening the `syncHTTPProxy` function
  pkg/controller/master/setting/http_proxy.go
Labels: backport-to/v1.4, backport-to/v1.3

#6242 harvester upgrade lookup enhancements
  pkg/controller/master/upgrade/version_syncer.go
  pkg/controller/master/upgrade/version_syncer_test.go
  pkg/util/fakeclients/version.go
Labels: backport-to/v1.4

#6447 http-proxy doesn't allow it to be reset to its default value
  pkg/webhook/resources/setting/validator.go
  pkg/webhook/resources/setting/validator_test.go
Labels: area/admission-webhook, need-rebase

#6608 fix: upgrade to rancher v2.9.2
  package/upgrade/upgrade_manifests.sh
Labels: backport-to/v1.4

#6640 Fix incorrect variable name in upgrade_node
  package/upgrade/upgrade_node.sh
Labels: backport-to/v1.4

#6576 enhancement: storage network webhook checks vcluster statefulset volume
  pkg/util/constants.go
  pkg/webhook/resources/setting/validator.go
Labels: backport-to/v1.4
