Repository harvester/harvester, pull requests merged in 2024-12, with the labels that each got.

#6826 bump(chart): bump Whereabouts to v0.7.0
  deploy/charts/harvester/values.yaml
Labels: status/stale

#7115 chore: add v1.4.0 min version
  package/upgrade-matrix.yaml
Labels: backport-to/v1.4

#7133 fine tune drain helper to skip hot plug volumes
  pkg/util/drainhelper/helper.go
Labels: backport-to/v1.3, backport-to/v1.4

#7103 [Backport v1.3] Fix crash on invalid JSON data
  pkg/indexeres/indexer.go
  pkg/webhook/resources/templateversion/validator.go
Labels: area/backend, priority/0, area/admission-webhook, severity/1, reproduce/always

#7104 [Backport v1.4] Fix crash on invalid JSON data
  pkg/indexeres/indexer.go
  pkg/webhook/resources/templateversion/validator.go
Labels: area/backend, priority/0, area/admission-webhook, severity/1, reproduce/always

#7049 feat: remove restriction of only checking default value
  pkg/webhook/resources/storageclass/validator.go
Labels: backport-to/v1.4

#7263 Bump eventrouter to v0.3.3
  package/upgrade/lib.sh
Labels: backport-to/v1.4

#7250 Fix incorrect unit in cpu usage dashboard
  package/upgrade/migrations/upgrade_manifests/v1.4.0/pre-hook.sh
Labels: backport-to/v1.4
