Repository harvester/harvester, pull requests merged in 2025-02, with the labels that each got.

#7431 ci: avoid creating duplicate releases
  .github/workflows/build.yml
Labels: backport-to/v1.5

#7440 fix(upgrade): exclude repo vm from live-migrate detection
  pkg/upgradehelper/vmlivemigratedetector/detector.go
Labels: backport-to/v1.4, backport-to/v1.5

#7421 Selectively update SC harvester-longhorn default SC annotation
  deploy/charts/harvester/templates/_helpers.tpl
  deploy/charts/harvester/templates/harvester-storageclass.yaml
Labels: backport-to/v1.5

#7170 VM Image Controller, Webhook and Download/Upload Refactor for Various Backend Support
  api/openapi-spec/swagger.json
  deploy/charts/harvester-crd/templates/harvesterhci.io_virtualmachineimages.yaml
  pkg/api/image/formatter.go
  pkg/api/image/schema.go
  pkg/api/volume/handler.go
  pkg/apis/harvesterhci.io/v1beta1/image.go
  pkg/apis/harvesterhci.io/v1beta1/openapi_generated.go
  pkg/controller/master/image/backing_image_controller.go
  pkg/controller/master/image/register.go
  pkg/controller/master/image/vm_image_controller.go
  pkg/controller/master/image/vm_image_controller_test.go
  pkg/image/backend/backend.go
  pkg/image/backingimage/backing_image_controller.go
  pkg/image/backingimage/backingimage.go
  pkg/image/backingimage/download.go
  pkg/image/backingimage/mutate.go
  pkg/image/backingimage/upload.go
  pkg/image/backingimage/validate.go
  pkg/image/cdi/cdi.go
  pkg/image/cdi/download.go
  pkg/image/cdi/mutate.go
  pkg/image/cdi/upload.go
  pkg/image/cdi/validate.go
  pkg/image/common/mutator.go
  pkg/image/common/operator.go
  pkg/image/common/validator.go
  pkg/util/image.go
  pkg/webhook/resources/virtualmachineimage/mutator.go
  pkg/webhook/resources/virtualmachineimage/mutator_test.go
  pkg/webhook/resources/virtualmachineimage/validator.go
  pkg/webhook/resources/virtualmachineimage/validator_test.go
  pkg/webhook/server/validation.go
  tests/integration/api/image_apis_test.go
Labels: backport-to/v1.5

#7528 Fix incorrect Grafana CPU Usage panel
  package/upgrade/migrations/upgrade_manifests/v1.4.2/pre-hook.sh
Labels: backport-to/v1.5

#7548 fix: migrate button incorrectly display
  pkg/api/vm/formatter.go
  pkg/util/virtualmachineinstance/virtualmachineinstance.go
Labels: backport-to/v1.4

#7565 remove emulated machine types
  deploy/charts/harvester/values.yaml
Labels: backport-to/v1.5

#7551 Add vm migration Grafana dashboard in upgrade path
  package/upgrade/migrations/upgrade_manifests/v1.4.2/pre-hook.sh
Labels: backport-to/v1.5

#7579 fix: upgrade: ensure passive.img is sparse before upgrading OS
  package/upgrade/upgrade_node.sh
Labels: backport-to/v1.4, backport-to/v1.5

#7608 fix(upgrade): not copying reason and msg from job to upgrade if success
  pkg/controller/master/upgrade/job_controller.go
Labels: backport-to/v1.4, backport-to/v1.5

#7649 Bump virtctl to v1.4.0
  package/upgrade/Dockerfile
Labels: backport-to/v1.5

#7114 feat: add refreshIntervalInSeconds to backup target
  pkg/controller/master/backup/backup_metadata.go
  pkg/controller/master/backup/backup_target.go
  pkg/controller/master/backup/util.go
  pkg/settings/settings_helper.go
  pkg/util/constants.go
  pkg/webhook/resources/setting/validator.go
Labels: backport-to/v1.4, backport-to/v1.5

#7704 fix: ignore VMBackup/VMImage if dependency is not existent
  pkg/controller/master/backup/backup_metadata.go
Labels: pr-backport-to/v1.4

#7725 Added default nodePlacement in kubevirt cr
  deploy/charts/harvester/values.yaml
Labels: pr-backport-to/v1.4, pr-backport-to/v1.5
