Repository harvester/harvester, pull requests merged in 2025-04, with the labels that each got.

#7977 fix(upgrade_manifest): fix getting longhorn-v2-data-engine-enabled if value is empty
  package/upgrade/upgrade_manifests.sh
Labels: pr-backport-to/v1.4, pr-backport-to/v1.5

#7964 fix upgrade matrix and build
  package/upgrade-matrix.yaml
Labels: area/build-package

#7991 image/cdi: add validator for VMImage with CDI backend
  pkg/api/volume/handler.go
  pkg/api/volume/schema.go
  pkg/image/cdi/validate.go
  pkg/image/common/validator.go
  pkg/util/volume.go
  pkg/webhook/resources/virtualmachineimage/validator.go
  pkg/webhook/server/validation.go
Labels: pr-backport-to/v1.5

#8034 image/download: ensure the VM Image is imported before download
  pkg/image/backingimage/download.go
  pkg/image/cdi/download.go
Labels: pr-backport-to/v1.5
